server:
  port: 8081

logging:
  config: classpath:logback-spring.xml
  logback:
    level: info #info ,debug
    path: D://test
    appname: logweb

#访问地址http://127.0.0.1:(port)/swagger-ui.html
swagger:
  enabled: true

## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  ## Mybatis 配置
mybatis:
  typeAliasesPackage: org.spring.springboot.domain
  mapperLocations: classpath:mapper/*.xml