server:
  port: 8081

logging:
  config: classpath:logback-spring.xml
  logback:
    level: info #info ,debug
    path: D://test
    appname: logweb

#http://127.0.0.1:(port)/swagger-ui.html
swagger:
  enabled: true